version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: lottery-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Next.js应用
  app:
    build: .
    container_name: lottery-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your_nextauth_secret_key_here}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
      - DEFAULT_ROOM_ID=${DEFAULT_ROOM_ID:-main_room}
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: 