version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: lottery-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Next.js应用
  app:
    build: .
    container_name: lottery-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
      - DEFAULT_ROOM_ID=${DEFAULT_ROOM_ID:-main_room}
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: 